// Mocks generated by Mockito 5.4.6 from annotations
// in myapp/test/mocks/mock_definitions.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i12;

import 'package:cloud_firestore/cloud_firestore.dart' as _i3;
import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:flutter/material.dart' as _i16;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i20;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:myapp/data/achievements/achievement_definitions.dart' as _i17;
import 'package:myapp/data/achievements/user_achievement_profile.dart' as _i18;
import 'package:myapp/models/category.dart' as _i6;
import 'package:myapp/models/habit.dart' as _i10;
import 'package:myapp/models/task.dart' as _i14;
import 'package:myapp/services/achievement_service.dart' as _i5;
import 'package:myapp/services/auth_service.dart' as _i7;
import 'package:myapp/services/category_service.dart' as _i15;
import 'package:myapp/services/genkit_service.dart' as _i19;
import 'package:myapp/services/habit_service.dart' as _i9;
import 'package:myapp/services/notification_service.dart' as _i4;
import 'package:myapp/services/task_service.dart' as _i13;
import 'package:timezone/timezone.dart' as _i21;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserCredential_0 extends _i1.SmartFake
    implements _i2.UserCredential {
  _FakeUserCredential_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseFirestore_1 extends _i1.SmartFake
    implements _i3.FirebaseFirestore {
  _FakeFirebaseFirestore_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseAuth_2 extends _i1.SmartFake implements _i2.FirebaseAuth {
  _FakeFirebaseAuth_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNotificationService_3 extends _i1.SmartFake
    implements _i4.NotificationService {
  _FakeNotificationService_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAchievementService_4 extends _i1.SmartFake
    implements _i5.AchievementService {
  _FakeAchievementService_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCategory_5 extends _i1.SmartFake implements _i6.Category {
  _FakeCategory_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i7.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Stream<_i2.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i8.Stream<_i2.User?>.empty(),
      ) as _i8.Stream<_i2.User?>);

  @override
  bool get isSignedIn => (super.noSuchMethod(
        Invocation.getter(#isSignedIn),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<_i2.UserCredential> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailAndPassword,
          [
            email,
            password,
          ],
        ),
        returnValue: _i8.Future<_i2.UserCredential>.value(_FakeUserCredential_0(
          this,
          Invocation.method(
            #signInWithEmailAndPassword,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i8.Future<_i2.UserCredential>);

  @override
  _i8.Future<_i2.UserCredential> createUserWithEmailAndPassword(
    String? email,
    String? password,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUserWithEmailAndPassword,
          [
            email,
            password,
            name,
          ],
        ),
        returnValue: _i8.Future<_i2.UserCredential>.value(_FakeUserCredential_0(
          this,
          Invocation.method(
            #createUserWithEmailAndPassword,
            [
              email,
              password,
              name,
            ],
          ),
        )),
      ) as _i8.Future<_i2.UserCredential>);

  @override
  _i8.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> sendPasswordResetEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #sendPasswordResetEmail,
          [email],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateProfile({
    String? displayName,
    String? photoURL,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #displayName: displayName,
            #photoURL: photoURL,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #updateEmail,
          [email],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updatePassword(String? password) => (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [password],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>?> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i8.Future<Map<String, dynamic>?>.value(),
      ) as _i8.Future<Map<String, dynamic>?>);

  @override
  _i8.Future<void> updateLastLogin() => (super.noSuchMethod(
        Invocation.method(
          #updateLastLogin,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [HabitService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHabitService extends _i1.Mock implements _i9.HabitService {
  MockHabitService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.FirebaseFirestore get firestore => (super.noSuchMethod(
        Invocation.getter(#firestore),
        returnValue: _FakeFirebaseFirestore_1(
          this,
          Invocation.getter(#firestore),
        ),
      ) as _i3.FirebaseFirestore);

  @override
  _i2.FirebaseAuth get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeFirebaseAuth_2(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i2.FirebaseAuth);

  @override
  _i4.NotificationService get notificationService => (super.noSuchMethod(
        Invocation.getter(#notificationService),
        returnValue: _FakeNotificationService_3(
          this,
          Invocation.getter(#notificationService),
        ),
      ) as _i4.NotificationService);

  @override
  _i5.AchievementService get achievementService => (super.noSuchMethod(
        Invocation.getter(#achievementService),
        returnValue: _FakeAchievementService_4(
          this,
          Invocation.getter(#achievementService),
        ),
      ) as _i5.AchievementService);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i8.Stream<List<_i10.Habit>> getHabits() => (super.noSuchMethod(
        Invocation.method(
          #getHabits,
          [],
        ),
        returnValue: _i8.Stream<List<_i10.Habit>>.empty(),
      ) as _i8.Stream<List<_i10.Habit>>);

  @override
  _i8.Future<List<_i10.Habit>> getAllHabits() => (super.noSuchMethod(
        Invocation.method(
          #getAllHabits,
          [],
        ),
        returnValue: _i8.Future<List<_i10.Habit>>.value(<_i10.Habit>[]),
      ) as _i8.Future<List<_i10.Habit>>);

  @override
  _i8.Future<String> addHabit(_i10.Habit? habit) => (super.noSuchMethod(
        Invocation.method(
          #addHabit,
          [habit],
        ),
        returnValue: _i8.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #addHabit,
            [habit],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<_i10.Habit?> getHabitById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getHabitById,
          [id],
        ),
        returnValue: _i8.Future<_i10.Habit?>.value(),
      ) as _i8.Future<_i10.Habit?>);

  @override
  _i8.Future<List<_i10.Habit>> getHabitsByCategory(String? categoryName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHabitsByCategory,
          [categoryName],
        ),
        returnValue: _i8.Future<List<_i10.Habit>>.value(<_i10.Habit>[]),
      ) as _i8.Future<List<_i10.Habit>>);

  @override
  _i8.Future<void> updateHabit(_i10.Habit? habit) => (super.noSuchMethod(
        Invocation.method(
          #updateHabit,
          [habit],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteHabit(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteHabit,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> markHabitCompletion(
    String? habitId,
    DateTime? date,
    bool? completed,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markHabitCompletion,
          [
            habitId,
            date,
            completed,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> resetHabitProgress(String? habitId) => (super.noSuchMethod(
        Invocation.method(
          #resetHabitProgress,
          [habitId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TaskService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskService extends _i1.Mock implements _i13.TaskService {
  MockTaskService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<List<_i14.Task>> getTasks() => (super.noSuchMethod(
        Invocation.method(
          #getTasks,
          [],
        ),
        returnValue: _i8.Future<List<_i14.Task>>.value(<_i14.Task>[]),
      ) as _i8.Future<List<_i14.Task>>);

  @override
  List<_i14.Task> getTasksSync() => (super.noSuchMethod(
        Invocation.method(
          #getTasksSync,
          [],
        ),
        returnValue: <_i14.Task>[],
      ) as List<_i14.Task>);

  @override
  _i8.Future<_i14.Task?> getTask(String? taskId) => (super.noSuchMethod(
        Invocation.method(
          #getTask,
          [taskId],
        ),
        returnValue: _i8.Future<_i14.Task?>.value(),
      ) as _i8.Future<_i14.Task?>);

  @override
  _i8.Future<String?> addTask(_i14.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #addTask,
          [task],
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<bool> updateTask(_i14.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [task],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> deleteTask(String? taskId) => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [taskId],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> markTaskCompletion(
    String? taskId,
    DateTime? date,
    bool? completed,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markTaskCompletion,
          [
            taskId,
            date,
            completed,
          ],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<List<_i14.Task>> getTasksDueToday() => (super.noSuchMethod(
        Invocation.method(
          #getTasksDueToday,
          [],
        ),
        returnValue: _i8.Future<List<_i14.Task>>.value(<_i14.Task>[]),
      ) as _i8.Future<List<_i14.Task>>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CategoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryService extends _i1.Mock implements _i15.CategoryService {
  MockCategoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i6.Category>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i8.Future<List<_i6.Category>>.value(<_i6.Category>[]),
      ) as _i8.Future<List<_i6.Category>>);

  @override
  _i8.Future<_i6.Category> addCategory({
    required String? name,
    required _i16.IconData? icon,
    required _i12.Color? color,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCategory,
          [],
          {
            #name: name,
            #icon: icon,
            #color: color,
          },
        ),
        returnValue: _i8.Future<_i6.Category>.value(_FakeCategory_5(
          this,
          Invocation.method(
            #addCategory,
            [],
            {
              #name: name,
              #icon: icon,
              #color: color,
            },
          ),
        )),
      ) as _i8.Future<_i6.Category>);

  @override
  _i8.Future<void> updateCategory(_i6.Category? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [category],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteCategory(
    String? categoryId, {
    _i9.HabitService? habitService,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [categoryId],
          {#habitService: habitService},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i6.Category?> getCategoryById(String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoryById,
          [categoryId],
        ),
        returnValue: _i8.Future<_i6.Category?>.value(),
      ) as _i8.Future<_i6.Category?>);

  @override
  _i8.Future<_i6.Category?> getCategoryByName(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoryByName,
          [name],
        ),
        returnValue: _i8.Future<_i6.Category?>.value(),
      ) as _i8.Future<_i6.Category?>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i4.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool> requestPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> scheduleHabitReminder(_i10.Habit? habit) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleHabitReminder,
          [habit],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cancelHabitReminder(_i10.Habit? habit) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelHabitReminder,
          [habit],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> showTestNotification() => (super.noSuchMethod(
        Invocation.method(
          #showTestNotification,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cancelAllNotifications() => (super.noSuchMethod(
        Invocation.method(
          #cancelAllNotifications,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [AchievementService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAchievementService extends _i1.Mock
    implements _i5.AchievementService {
  MockAchievementService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> get recentlyUnlocked => (super.noSuchMethod(
        Invocation.getter(#recentlyUnlocked),
        returnValue: <String>[],
      ) as List<String>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> initialize(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [userId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i17.Achievement>> checkAchievements(
          List<_i10.Habit>? habits) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkAchievements,
          [habits],
        ),
        returnValue:
            _i8.Future<List<_i17.Achievement>>.value(<_i17.Achievement>[]),
      ) as _i8.Future<List<_i17.Achievement>>);

  @override
  _i8.Future<void> markAchievementsAsSeen(List<String>? achievementIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAchievementsAsSeen,
          [achievementIds],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i18.AchievementProgress? getAchievementProgress(String? achievementId) =>
      (super.noSuchMethod(Invocation.method(
        #getAchievementProgress,
        [achievementId],
      )) as _i18.AchievementProgress?);

  @override
  List<(_i17.Achievement, _i18.AchievementProgress)> getAchievementsByCategory(
          _i17.AchievementCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAchievementsByCategory,
          [category],
        ),
        returnValue: <(_i17.Achievement, _i18.AchievementProgress)>[],
      ) as List<(_i17.Achievement, _i18.AchievementProgress)>);

  @override
  void clearRecentlyUnlocked() => super.noSuchMethod(
        Invocation.method(
          #clearRecentlyUnlocked,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [GenkitService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGenkitService extends _i1.Mock implements _i19.GenkitService {
  MockGenkitService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  _i8.Future<String> testHelloFlow(String? name) => (super.noSuchMethod(
        Invocation.method(
          #testHelloFlow,
          [name],
        ),
        returnValue: _i8.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #testHelloFlow,
            [name],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<Map<String, dynamic>> processOnboardingAnswer(String? answer) =>
      (super.noSuchMethod(
        Invocation.method(
          #processOnboardingAnswer,
          [answer],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getHabitSuggestions(
          Map<String, dynamic>? userInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHabitSuggestions,
          [userInfo],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);
}

/// A class which mocks [FlutterLocalNotificationsPlugin].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterLocalNotificationsPlugin extends _i1.Mock
    implements _i20.FlutterLocalNotificationsPlugin {
  MockFlutterLocalNotificationsPlugin() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<bool?> initialize(
    _i20.InitializationSettings? initializationSettings, {
    _i20.DidReceiveNotificationResponseCallback?
        onDidReceiveNotificationResponse,
    _i20.DidReceiveBackgroundNotificationResponseCallback?
        onDidReceiveBackgroundNotificationResponse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [initializationSettings],
          {
            #onDidReceiveNotificationResponse: onDidReceiveNotificationResponse,
            #onDidReceiveBackgroundNotificationResponse:
                onDidReceiveBackgroundNotificationResponse,
          },
        ),
        returnValue: _i8.Future<bool?>.value(),
      ) as _i8.Future<bool?>);

  @override
  _i8.Future<_i20.NotificationAppLaunchDetails?>
      getNotificationAppLaunchDetails() => (super.noSuchMethod(
            Invocation.method(
              #getNotificationAppLaunchDetails,
              [],
            ),
            returnValue: _i8.Future<_i20.NotificationAppLaunchDetails?>.value(),
          ) as _i8.Future<_i20.NotificationAppLaunchDetails?>);

  @override
  _i8.Future<void> show(
    int? id,
    String? title,
    String? body,
    _i20.NotificationDetails? notificationDetails, {
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #show,
          [
            id,
            title,
            body,
            notificationDetails,
          ],
          {#payload: payload},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cancel(
    int? id, {
    String? tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [id],
          {#tag: tag},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cancelAll() => (super.noSuchMethod(
        Invocation.method(
          #cancelAll,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cancelAllPendingNotifications() => (super.noSuchMethod(
        Invocation.method(
          #cancelAllPendingNotifications,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> zonedSchedule(
    int? id,
    String? title,
    String? body,
    _i21.TZDateTime? scheduledDate,
    _i20.NotificationDetails? notificationDetails, {
    required _i20.AndroidScheduleMode? androidScheduleMode,
    String? payload,
    _i20.DateTimeComponents? matchDateTimeComponents,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #zonedSchedule,
          [
            id,
            title,
            body,
            scheduledDate,
            notificationDetails,
          ],
          {
            #androidScheduleMode: androidScheduleMode,
            #payload: payload,
            #matchDateTimeComponents: matchDateTimeComponents,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> periodicallyShow(
    int? id,
    String? title,
    String? body,
    _i20.RepeatInterval? repeatInterval,
    _i20.NotificationDetails? notificationDetails, {
    required _i20.AndroidScheduleMode? androidScheduleMode,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #periodicallyShow,
          [
            id,
            title,
            body,
            repeatInterval,
            notificationDetails,
          ],
          {
            #androidScheduleMode: androidScheduleMode,
            #payload: payload,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> periodicallyShowWithDuration(
    int? id,
    String? title,
    String? body,
    Duration? repeatDurationInterval,
    _i20.NotificationDetails? notificationDetails, {
    _i20.AndroidScheduleMode? androidScheduleMode =
        _i20.AndroidScheduleMode.exact,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #periodicallyShowWithDuration,
          [
            id,
            title,
            body,
            repeatDurationInterval,
            notificationDetails,
          ],
          {
            #androidScheduleMode: androidScheduleMode,
            #payload: payload,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i20.PendingNotificationRequest>>
      pendingNotificationRequests() => (super.noSuchMethod(
            Invocation.method(
              #pendingNotificationRequests,
              [],
            ),
            returnValue:
                _i8.Future<List<_i20.PendingNotificationRequest>>.value(
                    <_i20.PendingNotificationRequest>[]),
          ) as _i8.Future<List<_i20.PendingNotificationRequest>>);

  @override
  _i8.Future<List<_i20.ActiveNotification>> getActiveNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveNotifications,
          [],
        ),
        returnValue: _i8.Future<List<_i20.ActiveNotification>>.value(
            <_i20.ActiveNotification>[]),
      ) as _i8.Future<List<_i20.ActiveNotification>>);
}
